version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            - build
      - test-python-install:
          version: "3.6"
          requires:
            - build
      - test-python-install:
          version: "3.7"
          requires:
            - build
      - test-python-install:
          version: "3.8"
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
          - run: echo "A first hello"